FROM golang:1.16.6-alpine as build

RUN apk add ca-certificates=20191127-r5 --no-cache

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build .

FROM scratch

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /app/geolocation /usr/bin/geolocation

ENTRYPOINT ["/usr/bin/geolocation"]
