version: "3.9"
services:
  geo-scratch:
    image: geo-scratch
    build:
        context: .
        dockerfile: Dockerfile.scratch
    container_name: geo-scratch
    env_file:
      - .env
    ports:
      - 8080:8080